### ISSUE TITLE
프로젝트 파일 업로드 기능 관련

### ISSUE THREAD

**Issue by leehj050211** [BSM-Deploy/BSM-Deploy-Frontend#23]
![image](https://user-images.githubusercontent.com/80656849/235355352-dffc91c9-8020-49ec-b74f-969a14d4902f.png)
리액트 프로젝트에서 빌드된 파일 말고 프로젝트 폴더 자체를 업로드한 사람들이 많네요.
예시 파일 구조를 만들어도 사람들이 이해를 잘 못하는 것 같은데
지금 Next.js 프로젝트 업로드 기능처럼
프로젝트 폴더를 선택하면 자동으로 build 폴더 안에 파일들을 업로드하도록 기능을 개선하는건 어떨까요?

**Comment by jeongdonggyeom** [comment]
좋은 의견이네요!😄 반영하겠습니다!
